"""create scans

Revision ID: b962c56a059a
Revises:
Create Date: 2026-10-03 17:25:25.350509

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b962c56a059a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("dataset", sa.String(length=255), nullable=False),
        sa.Column("tumor_type", sa.String(length=50), nullable=False),
        sa.Column("plane", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_name"),
    )
    op.create_index(op.f("ix_scans_dataset"), "scans", ["dataset"], unique=False)
    op.create_index(op.f("ix_scans_title"), "scans", ["title"], unique=False)
    op.create_index(op.f("ix_scans_tumor_type"), "scans", ["tumor_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scans_tumor_type"), table_name="scans")
    op.drop_index(op.f("ix_scans_title"), table_name="scans")
    op.drop_index(op.f("ix_scans_dataset"), table_name="scans")
    op.drop_table("scans")
    # ### end Alembic commands ###
